export const ORG_SEO = {
  defaultKeywords: [
    "Austax Partners Advisory",
    "Tax Accountant Dandenong",
    "Accountant Dandenong",
    "Registered Tax Agent",
    "Accounting Services",
    "Bookkeeping Services",
    "BAS Agent",
    "Business Advisory",
    "Tax Returns",
    "Small Business Accountant",
  ] as const,

  homeKeywords: [
    "Austax Partners Advisory",
    "Tax Accountant Dandenong",
    "Accountant Near Dandenong",
    "Bookkeeping Services Dandenong",
    "Business Advisory Dandenong",
    "Registered Tax Agent Victoria",
    "Tax Returns Dandenong",
    "BAS and GST Services",
    "Small Business Accountant Victoria",
    "Personal and Business Tax Services",
  ] as const,

  aboutKeywords: [
    "Austax Partners Advisory",
    "Professional Accountant Dandenong",
    "Registered Tax Agent Dandenong",
    "Business Advisory Firm Victoria",
    "Accounting and Bookkeeping Experts",
    "Tax and Accounting Services Australia",
    "Small Business Tax Support",
    "Trusted Tax Accountant Victoria",
  ] as const,

  contactKeywords: [
    "Tax Accountant Contact Dandenong",
    "Bookkeeping Quote Dandenong",
    "Accounting Consultation Victoria",
    "Tax Return Help Dandenong",
    "BAS Agent Contact",
    "Business Advisory Enquiry",
    "Accountant Dandenong Contact",
    "Tax Services Australia Contact",
  ] as const,

  serviceBaseKeywords: [
    "Tax Services Dandenong",
    "Accounting Services Dandenong",
    "Bookkeeping Dandenong",
    "Business Advisory Victoria",
    "Tax Returns Australia",
    "BAS Services",
    "GST Services",
    "Registered Tax Agent",
    "Small Business Accounting",
    "Australia Tax Accountant",
  ] as const,
} as const;